import { Hono } from 'hono';

const app = new Hono();

app.post('/', async (c) => {
  try {
    const { text } = await c.req.json();
    
    if (!text) {
      return c.json({ error: 'Text is required' }, 400);
    }
    
    // Mock to development
    return c.json({ 
      summary: "This is a mock summary. In production, this would be generated by Gemini AI via n8n workflow." 
    });
  } catch (error) {
    console.error('Error summarizing text:', error);
    return c.json({ error: 'Failed to summarize text' }, 500);
  }
});

export default app;